-- +goose Up

-- HP/MP 欄位從 SMALLINT 擴展為 INTEGER，支援最大 9,999,999
ALTER TABLE characters ALTER COLUMN hp TYPE INTEGER;
ALTER TABLE characters ALTER COLUMN mp TYPE INTEGER;
ALTER TABLE characters ALTER COLUMN max_hp TYPE INTEGER;
ALTER TABLE characters ALTER COLUMN max_mp TYPE INTEGER;
ALTER TABLE character_buffs ALTER COLUMN delta_max_hp TYPE INTEGER;
ALTER TABLE character_buffs ALTER COLUMN delta_max_mp TYPE INTEGER;
